name: CMake Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup extern directory
      run: |
        if (Test-Path -Path "extern") {
            Remove-Item -Recurse -Force extern
        }
        mkdir extern
        cd extern
        # SDK setup will be manual for now due to Adobe licensing

    - name: Clean and Configure CMake
      run: |
        if (Test-Path -Path "build") {
            Remove-Item -Recurse -Force build
        }
        mkdir build
        cd build
        cmake -S .. -B .

    - name: Build
      run: |
        cd build
        cmake --build . --config Release

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: CrazyCurves-plugin
        path: build/Release/CrazyCurves.aex
        retention-days: 90