name: CMake Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Clean and Configure CMake
      run: |
        if (Test-Path -Path "build") {
            Remove-Item -Recurse -Force build
        }
        mkdir build
        cd build
        # Build core components only without AE SDK
        cmake -S .. -B .

    - name: Build
      run: |
        cd build
        cmake --build . --config Release

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: CrazyCurves-core
        path: build/Release/*.dll
        retention-days: 90