name: CMake Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      shell: pwsh
      run: |
        if (Test-Path -Path "build") {
            Remove-Item -Recurse -Force build
        }
        New-Item -ItemType Directory -Path build
        cd build
        cmake -B . -S .. -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: |
        cd build
        cmake --build . --config ${{env.BUILD_TYPE}}

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: CrazyCurves-windows
        path: build/${{env.BUILD_TYPE}}/*.dll
        retention-days: 90